### ISSUE TITLE
Broken link in docs contributions

### ISSUE THREAD

**Issue by jameswilson** [terra-ops/terra-cli#116]
Wanted to contribute some fixes to the documentation, while it's fresh, since I'm trying to get up and running right now, but couldn't. Had a look through https://github.com/terra-ops/docs  but that didn't seem like the right place (just one master branch with very little docs).

Basically, the link in the Terra documentation that says "improve the docs" in the Documentation & Issues section is broken. http://terra.readthedocs.io/#documentation-issues

It points to a devshop url: https://github.com/terra/devshop/edit/0.x/README.md

I don't know much about that readthedocs platform to be able to figure out where the source code for the docs are located.

**Comment by jameswilson** [comment]
OMG.  Just found it (facepalm).

https://github.com/terra-ops/terra-cli/tree/master/docs

I'll submit a pull request.

**Comment by jameswilson** [comment]
Hrm. I also noticed the link to the Gitter Chat reads "Join the chat at https://gitter.im/opendevshop/devshop"  but points to https://gitter.im/terra-ops/terra-cli ! 

I'll fix that too.

**Comment by jonpugh** [comment]
Ahhh , thanks so much @jameswilson !
