### ISSUE TITLE
Terra cannot run after initial installation

### ISSUE THREAD

**Issue by theodorosploumis** [terra-ops/terra-cli#16]
I am on Ubuntu 14.04. I follow the instructions from https://github.com/terra-ops/terra-app/blob/master/docs/install.md.

Installation does not output any error but when I simple run `terra` it says command not found.

If I run the 'terra' file on its folder (~/.composer/vendor/terra/terra-app) with php it runs OK.
`php ~/.composer/vendor/terra/terra-app/terra`

Notice that I already had **composer, docker, docker-compose** installed on my system.

**Comment by jonpugh** [comment]
It's still a bit of a pain to make sure the executable file is in your path.

The shortest way is to just clone the repo, `compose install` then make a symlink directly in your /usr/local/bin:

```
sudo ln -s /home/username/Repos/terra-app/terra /usr/local/bin
```

This is also the easiest way to help develop terra.

**Comment by jonpugh** [comment]
The `composer global require` install method should be fixed now!

However, just like when installing drush, you must add the composer vendor bin path to your system path:

> Now add Drush to your system path by placing export PATH="$HOME/.composer/vendor/bin:$PATH" into your ~/.bash_profile (Mac OS users) or into your ~/.bashrc (Linux users).

Please give it another shot and close this issue if it works!

Thanks,
Jon

**Comment by jonpugh** [comment]
@theodorosploumis Can you confirm that you can install terra now?  If so, can you close this issue?

Thanks!

**Comment by theodorosploumis** [comment]
I 've installed terra globally with composer and it works now (docs from http://terra.readthedocs.org/en/latest/install/)
