### ISSUE TITLE
Inaccurate reporting when env:enable fails

### ISSUE THREAD

**Issue by nateswart** [terra-ops/terra-cli#30]
If `terra env:enable` fails the process continues to run and claims the environment was enabled. For instance, I received this error:

`DOCKER > Couldn't connect to Docker daemon - you might need to run 'boot2docker up'.`

But then subsequently received the following output:

`Environment enabled!  Available at http://mysite.local.Macintosh.local and http://localhost:
Write a drush alias file to /Users/nate/.drush/mysite.aliases.drushrc.php ?`

It seems as though the process should exit on a failure.

**Comment by jonpugh** [comment]
Thanks for working on that!  Merged.
