### ISSUE TITLE
Inaccurate use of localhost

### ISSUE THREAD

**Issue by nateswart** [terra-ops/terra-cli#31]
Localhost is assumed in a number of places. I believe this only functions on Linux and needs to be dynamic on non-linux systems.

The following commands:
`terra status`
`terra app:status`
`terra env:status`

all report localhost:[port] when systems using boot2docker need a specific IP address (192.168.99.100) in my case. 

Additionally, the use of localhost can be found in the drush aliases.

**Comment by nateswart** [comment]
It appears that Kitematic is picking up the correct IP and port, so it may be as simple as using whatever basic process they are using.

![kitematic_and_terra_setup_docs_ _evernote_basic_and_dockerfile_-__users_nate_projects_public_docker-drush_-_atom](https://cloud.githubusercontent.com/assets/839888/8582644/28317908-2596-11e5-9ac9-a82cad937bbd.png)

**Comment by jonpugh** [comment]
While I am down with adding docker machine, still think we should have a default hostname.

Let's make the default hostname a configuration item, it could ask the first time you run terra.

**Comment by jonpugh** [comment]
We resolved this for now in #56.  Terra now asks you the default host for each App.
