### ISSUE TITLE
support for specific git branches in environments

### ISSUE THREAD

**Issue by badri** [terra-ops/terra-cli#68]
Hi,
It would be great to add support for specifying git branch while creating new environments. Typically, most agile + git workflows involve feature branches and would be a nice enhancement IMO.

**Comment by jonpugh** [comment]
Yes, absolutely!

This was always the plan in my head, I just never got around to doing it or writing down that this was the plan. 

Thanks for taking the initiative!!

I've commented on your PR with a few more things I'd like to change before merging.

**Comment by jonpugh** [comment]
Thanks, @badri!

You can now specify "--ref" when adding an environment
