### ISSUE TITLE
path name created with spaces

### ISSUE THREAD

**Issue by badri** [terra-ops/terra-cli#71]
The path name is created from environment name during the `environment:add` stage without any processing.

```
$ terra environment:add
Which app? 
  [d7   ] d7
  [kalvi] kalvi
 > kalvi
Environment name? test env
Path: (/home/lakshmi/Apps/kalvi/test env)
```

Should the environment name be sanitized a bit before creating the path?

**Comment by jonpugh** [comment]
I commented on your PR.  I think we should prevent spaces and special characters from being used in environment names, then we don't have to worry about file path sanitization.

**Comment by jonpugh** [comment]
Thanks! fixed.
