### ISSUE TITLE
Rename repo to terra-cli

### ISSUE THREAD

**Issue by jonpugh** [terra-ops/terra-cli#75]
It's time.
- [x] Rename the repo.
- [x] Remove the packagist package, create a new one at `terra/cli`
- [x] Alter terra-ops/terra-queue/composer.json to include terra/cli instead.

**Comment by EclipseGc** [comment]
++

**Comment by jonpugh** [comment]
Ok!  Here goes!

I promise not to put another thing called "terra-app" here so it always redirects.

**Comment by jonpugh** [comment]
I'm reopening until I'm done renaming everything.
